default: &default

  default_locale: 'en'
  available_locales: 
    - en

  media_streams:
    defaults:
      video: 480p
      audio: 192k
    video:
    audio:

  contribution_types:
    interviewee: 'interviewee'
    interviewer: 'interviewer'
    cinematographer: 'cinematographer'
    sound: 'sound'
    producer: 'producer'
    other_attender: 'other_attender'
    quality_manager_interviewing: 'quality_manager_interviewing'
    transcriptor: 'transcriptor'
    segmentator: 'segmentator'
    translator: 'translator'
    proofreader: 'proofreader'
    research: 'research'

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
