default: &default

  media_streams:
    defaults:
      video: 480p
      audio: 192k
    video:
      240p: https://medien.cedis.fu-berlin.de/cdoh/cdoh/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_240p.mp4
      480p: https://medien.cedis.fu-berlin.de/cdoh/cdoh/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_480p.mp4
      720p: https://medien.cedis.fu-berlin.de/cdoh/cdoh/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_720p.mp4
    audio:
      128k: https://medien.cedis.fu-berlin.de/cdoh/cdoh/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_128k.mp3
      192k: https://medien.cedis.fu-berlin.de/cdoh/cdoh/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_192k.mp3
      256k: https://medien.cedis.fu-berlin.de/cdoh/cdoh/#{archive_id}/#{archive_id}_#{tape_count}_0#{tape_number}_256k.mp3

  contribution_types:
    interviewee: 'interviewee'
    interviewer: 'interviewer'
    transcriptor: 'transcriptor'
    translator: 'translator'
    segmentator: 'segmentator'
    cinematographer: 'cinematographer'
    quality_manager_interviewing: 'quality_manager_interviewing'
    proofreader: 'proofreader'
    research: 'research'
    sound: 'sound'
    other_attender: 'other_attender'
    producer: 'producer'

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

