default: &default

  media_streams:
    defaults:
      audio: 480p
    audio:
      480p: https://thigrandi.fernuni-hagen.de:8443/geschichte/ArchivDeutschesGedaechtnis/OnlineArchiv/#{archive_id}_#{tape_count}_0#{tape_number}.mp3
    video:

  contribution_types:
    interviewee: 'interviewee'
    interviewer: 'interviewer'
    cinematographer: 'cinematographer'
    sound: 'sound'
    producer: 'producer'
    other_attender: 'other_attender'
    quality_manager_interviewing: 'quality_manager_interviewing'
    transcriptor: 'transcriptor'
    segmentator: 'segmentator'
    translator: 'translator'
    proofreader: 'proofreader'
    research: 'research'

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
