default: &default

  media_streams:
    defaults:
      audio: 480p
    audio:
      # 480p: https://medien.cedis.fu-berlin.de/zwar/hagen/#{archive_id}_#{tape_count}_0#{tape_number}.mp3
      480p: https://thigrandi.fernuni-hagen.de:8443/geschichte/ArchivDeutschesGedaechtnis/OnlineArchiv/#{archive_id}_#{tape_count}_0#{tape_number}.mp3
    video:
      240p: https://thigrandi.fernuni-hagen.de:8443/geschichte/ArchivDeutschesGedaechtnis/OnlineArchiv/#{archive_id}_#{tape_count}_0#{tape_number}_sd240p.mp4
      480p: https://thigrandi.fernuni-hagen.de:8443/geschichte/ArchivDeutschesGedaechtnis/OnlineArchiv/#{archive_id}_#{tape_count}_0#{tape_number}_sd480p.mp4
      720p: https://thigrandi.fernuni-hagen.de:8443/geschichte/ArchivDeutschesGedaechtnis/OnlineArchiv/#{archive_id}_#{tape_count}_0#{tape_number}_sd720p.mp4


  contribution_types:
    interviewee: 'interviewee'
    interviewer: 'interviewer'
    transcriptor: 'transcriptor'
    translator: 'translator'
    segmentator: 'segmentator'
    cinematographer: 'cinematographer'
    quality_manager_interviewing: 'quality_manager_interviewing'
    proofreader: 'proofreader'
    research: 'research'
    sound: 'sound'
    other_attender: 'other_attender'
    producer: 'producer'

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

