default: &default

  contribution_types:
    interviewee: 'interviewee'
    interviewer: 'interview'
    transcriptor: 'transcript'
    translator: 'translation'
    segmentator: 'segmentation'
    research: 'research'
    sound: 'sound'
    other_attender: 'other_attender'
    producer: 'producer'

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

