available_locales:
  - de

default_locale: de

project_name:
  de: 'Hagen Interviewsammlung'

project_id: 'hagen'

project_shortname: 'HAGIS'

project_initials: 'HA'

project_domain: 'hagen-archiv.de'

cifs_share: '/mnt/hagen.cedis.fu-berlin.de/data/'

streaming_server: 'rtmpt://stream.cedis.fu-berlin.de/hagen-archiv'

meta_keywords:
  de: ''

contact_email: 'mail@hagen-archiv.de'

smtp_server: 'mail.fu-berlin.de'