available_locales:
  - de

default_locale: de

project_name:
  de: 'Zwangsarbeit 1939-1945. Erinnerungen und Geschichte.'

project_shortname: 'ZWAR'

project_initials: 'HA'

project_domain: 'zwangsarbeit-archiv.de'

ifs_share: '/mnt/eaz-diga.cedis.fu-berlin.de/data/'

streaming_server: 'rtmpt://stream.cedis.fu-berlin.de/zwangsarbeit-archiv'

meta_keywords:
  de: 'Speer, Befreiung, Zwangsarbeit, Sklavenarbeit, Geschichte, Nationalsozialismus, Hitler, Sauckel, Oral History, biographisch, Archiv, Gedenken, Literatur, Quellen, Interviews, Erinnerungen, Stimmen, Fotografien, Entschädigung, Konzentrationslager, KZ, Ukrainerinnen, Tschechen, Polen, Ostarbeiter, Ostarbeiterinnen, Stiftung EVZ, audiovisuelle Archive, multimedial, Inventarisierung, Museum, Universität, Digitalisierung, Segmentierung, Übersetzung, STO, IMI, Militärinternierte, Auschwitz, Buchenwald, Flossenbürg, Zigeuner, Roma, Sinti, Displaced Person, Zwangsarbeiterlager, Zweiter Weltkrieg, Drittes Reich, 1939, 1940, 1941, 1942, 1943, 1944, 1945, Ghetto, Arbeitserziehungslager, Vernichtung, Verfolgung, Widerstand, Litauen, Moldawien, Ukraine, Polen, Italien, Norwegen, vergessene Opfer, Kriegskinder, Germanisierung, Deportation, Platoprojekt, Alexander von Plato, Fernuniversität, Hitlers Sklaven, SS, Gestapo, Wehrmacht'

contact_email: 'mail@zwangsarbeit-archiv.de'

smtp_server: 'mail.fu-berlin.de'