available_locales:
  - de

default_locale: de

project_name:
  de: 'Oral History Archive'

project_id: 'hagen'

project_shortname: 'LUSIR'

project_initials: 'DG'

project_domain: 'da02.cedis.fu-berlin.de'

cifs_share: '/mnt/hagen.cedis.fu-berlin.de/data/'

streaming_server: 'rtmp://stream03.cedis.fu-berlin.de/zwangsarbeit-archiv'

meta_keywords:
  de: ''

contact_email: 'almut.leh@fernuni-hagen.de'

smtp_server: 'mail.fu-berlin.de'

archive_categories: []