default: &default

  available_locales:
    - de
    - en

  default_locale: de

  # use 2- or 3-letter country-code
  # have a look at https://github.com/alphabetum/iso-639 for possible methods
  alpha: 'alpha2'

  contribution_types:
    interviewee: 'interviewee'
    interviewer: 'interview'
    transcriptor: 'transcript'
    translator: 'translation'
    segmentator: 'segmentation'

  project_name:
    de: 'Deutsches Gedächtnis'

  project_id: 'hagen'

  project_shortname: 'LUSIR'

  project_initials: 'DG'

  project_domain: 'da02.cedis.fu-berlin.de'

  external_links:
    conditions:
      de: 'https://www.fernuni-hagen.de/geschichteundbiographie/deutschesgedaechtnis/nutzungsbedingungen.shtml'
    usage_application:
      de: 'https://deutsches-gedaechtnis.fernuni-hagen.de/archiv/registrieren?locale=de'
    privacy_protection:
      de: 'https://www.fernuni-hagen.de/geschichteundbiographie/deutschesgedaechtnis/datenschutzbestimmungen.shtml'
    annotation_guidelines:
      de: 'https://www.fernuni-hagen.de/geschichteundbiographie/deutschesgedaechtnis/archivnutzung.shtml'
    team:
      de: 'https://www.fernuni-hagen.de/geschichteundbiographie/deutschesgedaechtnis/oateam.shtml'
    contact:
      de: 'https://www.fernuni-hagen.de/geschichteundbiographie/deutschesgedaechtnis/kontakt.shtml'
    legal_info:
      de: 'http://www.fernuni-hagen.de/impressum.shtml'

  cifs_share: '/mnt/hagen.cedis.fu-berlin.de/data/'

  storage_dir: '/mnt/hagen.cedis.fu-berlin.de/data/archiv_backup'
  photo_storage_dir: '/mnt/hagen.cedis.fu-berlin.de/data/archiv_backup/bilder'
  archive_management_dir: '/mnt/hagen.cedis.fu-berlin.de/data/archiv_backup/redaktionssystem'
  repository_dir: '/mnt/hagen.cedis.fu-berlin.de/data/archiv_backup/archiv_dis'

  streaming_server: 'rtmp://stream03.cedis.fu-berlin.de/zwangsarbeit-archiv'

  meta_keywords:
    de: ''

  contact_email: 'deutsches-gedaechtnis@fernuni-hagen.de'

  smtp_server: 'mail.fu-berlin.de'

  person_properties:
    - id: 'person_reference'
      source: 'registry_entry'
    - id: 'birth_locations'
      source: 'registry_reference_type'
    - id: 'language_id'
      source: 'language'
      use_as_facet: true
    #- id: 'forced_labor_groups'
      #source: 'registry_entry'
      #use_as_facet: true
    - id: 'gender'
      source: 'person'
      use_as_facet: true
      values:
        female: 'female'
        male: 'male'
    - id: 'year_of_birth'
      source: 'person'
      use_as_facet: true
    #- id: 'decade_of_birth'
      #source: 'person'
      #use_as_facet: true
      #values:
        #"1900s": "1900s"
        #"1910s": "1910s"
        #"1920s": "1920s"
        #"1930s": "1930s"
    #- id: 'forced_labor_fields'
      #source: 'registry_entry'
      #use_as_facet: true
    - id: 'forced_labor_habitations'
      source: 'registry_entry'
      # use_as_facet: true
    - id: 'home_location'
      source: 'registry_reference_type'
      # use_as_facet: true
    - id: 'forced_labor_locations'
      source: 'registry_reference_type'
    - id: 'deportation_locations'
      source: 'registry_reference_type'
    - id: 'return_locations'
      source: 'registry_reference_type'
    - id: 'collection_id'
      source: 'collection'
      use_as_facet: true 
  #person_properties:
    #- id: 'person_reference'
      #source: 'registry_entry'
      #descriptor: 'Person'
    #- id: 'pseudonym'
      #source: 'registry_entry'
      #descriptor: 'Pseudonym'
      #use_as_facet: true
    #- id: 'gender'
      #source: 'registry_entry'
      #descriptor: 'Geschlecht'
      #use_as_facet: true
    #- id: 'interview_dates'
      #source: 'registry_reference_type'
      #use_as_facet: true
    #- id: 'birth_dates'
      #source: 'registry_reference_type'
      #use_as_facet: true
    #- id: 'birth_locations'
      #source: 'registry_reference_type'
      #use_as_facet: true
    #- id: 'home_locations'
      #source: 'registry_reference_type'
      #use_as_facet: true
    #- id: 'profession'
      #source: 'registry_entry'
      #descriptor: 'Beruf'
      #use_as_facet: true
    #- id: 'professional_position'
      #source: 'registry_entry'
      #descriptor: 'Stellung im Beruf'
      #use_as_facet: true
    #- id: 'industry'
      #source: 'registry_entry'
      #descriptor: 'Wirtschaftsbereich'
      #use_as_facet: true

  uses_map: false # Must be "false" for all projects except ZWAR until the map has been generalized.

  has_newsletter: false

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

