default: &default

  media_streams:
    defaults:
      video: 480p
    video:
      240p: https://medien.cedis.fu-berlin.de/eog/interviews/mog/#{archive_id}/#{archive_id}_01_01_240p.mp4
      480p: https://medien.cedis.fu-berlin.de/eog/interviews/mog/#{archive_id}/#{archive_id}_01_01_480p.mp4
      720p: https://medien.cedis.fu-berlin.de/eog/interviews/mog/#{archive_id}/#{archive_id}_01_01_720p.mp4

  # 'Informants' and 'Interviewer' are specific for Dédalo, zwar-default is 'interviewee' and 'interview'
  contribution_types:
    interviewee: 'interviewee'
    interviewer: 'interviewer'
    transcriptor: 'transcriptor'
    translator: 'translator'
    segmentator: 'segmentator'
    research: 'research'
    sound: 'sound'
    other_attender: 'other_attender'
    producer: 'producer'

development:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

