available_locales:
  - de

default_locale: de

project_name:
  de: 'Oral History Archive'

project_id: 'hagen'

project_shortname: 'LUSIR'

project_initials: 'DG'

project_domain: 'da02.cedis.fu-berlin.de'

cifs_share: '/mnt/hagen.cedis.fu-berlin.de/data/'

streaming_server: 'rtmp://stream03.cedis.fu-berlin.de/zwangsarbeit-archiv'

meta_keywords:
  de: ''

contact_email: 'almut.leh@fernuni-hagen.de'

smtp_server: 'mail.fu-berlin.de'

person_properties:
  - id: 'person_reference'
    source: 'registry_entry'
    descriptor: 'Person'
  - id: 'birth_locations'
    source: 'registry_reference_type'
  - id: 'home_locations'
    source: 'registry_reference_type'
    use_as_facet: true

uses_map: false # Currently must be "false" for all projects except ZWAR.