---
- :name: Interview bearbeiten und anlegen
  :permissions:
  - :name: Interview create
    :klass: Interview
    :action_name: create
  - :name: Interview update
    :klass: Interview
    :action_name: update
  - :name: Interview show
    :klass: Interview
    :action_name: show
- :name: Personen anlegen und bearbeiten
  :permissions:
  - :name: Person show
    :klass: Person
    :action_name: show
  - :name: Person create
    :klass: Person
    :action_name: create
  - :name: Person destroy
    :klass: Person
    :action_name: destroy
  - :name: Person update
    :klass: Person
    :action_name: update
- :name: Schlagwörter vergeben
  :permissions:
  - :name: RegistryReference show
    :klass: RegistryReference
    :action_name: show
  - :name: RegistryReference create
    :klass: RegistryReference
    :action_name: create
  - :name: RegistryReference destroy
    :klass: RegistryReference
    :action_name: destroy
  - :name: RegistryReference update
    :klass: RegistryReference
    :action_name: update
- :name: Benutzer verwalten
  :permissions:
  - :name: UserRegistrationProject update
    :klass: UserRegistrationProject
    :action_name: update
  - :name: UserRole create
    :klass: UserRole
    :action_name: create
  - :name: UserRole destroy
    :klass: UserRole
    :action_name: destroy
- :name: Mitwirkende zuweisen
  :permissions:
  - :name: Contribution create
    :klass: Contribution
    :action_name: create
  - :name: Contribution destroy
    :klass: Contribution
    :action_name: destroy
  - :name: Interview show
    :klass: Interview
    :action_name: show
- :name: Import
  :permissions:
  - :name: Upload create
    :klass: Upload
    :action_name: create
- :name: Register bearbeiten
  :permissions:
  - :name: RegistryEntry show
    :klass: RegistryEntry
    :action_name: show
  - :name: RegistryEntry create
    :klass: RegistryEntry
    :action_name: create
  - :name: RegistryEntry destroy
    :klass: RegistryEntry
    :action_name: destroy
  - :name: RegistryEntry update
    :klass: RegistryEntry
    :action_name: update
  - :name: RegistryHierarchy create
    :klass: RegistryHierarchy
    :action_name: create
  - :name: RegistryHierarchy destroy
    :klass: RegistryHierarchy
    :action_name: destroy
  - :name: RegistryName show
    :klass: RegistryName
    :action_name: show
  - :name: RegistryName create
    :klass: RegistryName
    :action_name: create
  - :name: RegistryName destroy
    :klass: RegistryName
    :action_name: destroy
  - :name: RegistryName update
    :klass: RegistryName
    :action_name: update
