job_description:
  'Studentin/Student': 'Studenten'
  'k. A. (Beruf)': 'Sonstige / ohne Angabe'
  'Lehrerin/Lehrer': 'Lehrer'
  'Wissenschaftlerin/Wissenschaftler': 'Wissenschaftler'
  'Journalistin/Journalist': 'Journalisten'
  'Other': 'Sonstige / ohne Angabe'
  'Schülerin/Schüler': 'Schüler'
  'Dozentin/Dozent': 'Dozenten'
  'Mitarbeiterin/Mitarbeiter (Museen/Gedenkstätten)': 'Mitarbeiter Museen/Gedenkst.'
  'Mitarbeiterin /Mitarbeiter (Museen / Gedenkstätten)': 'Mitarbeiter Museen/Gedenkst.'
  'Dozent': 'Dozenten'
  'Mitarbeit': 'Mitarbeiter Museen/Gedenkst.'
  'University Student': 'Studenten'
  'Filmemacherin/Filmemacher': 'Filmemacher'
  'Dozent(in)/Forscher(in)': 'Dozenten'
  'Teacher': 'Lehrer'
  'Student(in)': 'Studenten'
  'Lecturer': 'Dozenten'
  'Staff Member (Museums/Memorial Sites)': 'Mitarbeiter Museen/Gedenkst.'
  'Staff Member (museums/memorial sites)': 'Mitarbeiter Museen/Gedenkst.'
  'Lehrer(in)': 'Lehrer'
  'Mitarbeiter(in) (Museen/Gedenkstätten)': 'Mitarbeiter Museen/Gedenkst.'
  'Projektmitarbeiter': 'Sonstige / ohne Angabe'
  'School Student': 'Schüler'
  'Mitarbeiterin /Mitarbeiter (Museen / Gedenkst?tten)': 'Mitarbeiter Museen/Gedenkst.'
  'Journalist': 'Journalisten'
  'Journalist(in)': 'Journalisten'
  'Filmemacher(in)': 'Filmemacher'
  'Lecturer/Researcher': 'Dozenten'
  'Schüler(in)': 'Schüler'
  'Sch?lerin/Sch?ler': 'Schüler'
  'Sonstiges': 'Sonstige / ohne Angabe'
research_intentions:
  'Persönliches Interesse': 'Persönl. Interesse / Sonstiges'
  'Bildungsarbeit': 'Bildungsarbeit'
  'Familienforschung': 'Familienforschung'
  'Sonstiges': 'Persönl. Interesse / Sonstiges'
  'Schulprojekt/Referat': 'Schulprojekt/Referat'
  'Wissenschaftliche Publikation': 'Wissenschaftl. Publikation'
  'Universitäre Lehre': 'Universitäre Lehre'
  'Pressepublikation': 'Pressepublikation'
  'Ausstellung': 'Ausstellung'
  'Dokumentarfilm': 'Dokumentarfilm'
  'Pers?nliches Interesse': 'Persönl. Interesse / Sonstiges'
  'Genealogy': 'Familienforschung'
  'Dissertation': 'Dissertation'
  'Private Interest/Other': 'Persönl. Interesse / Sonstiges'
  'Kunstprojekt': 'Kunstprojekt'
  'Mitarbeit': 'Persönl. Interesse / Sonstiges'
  'Educational Work': 'Bildungsarbeit'
  'Dissertation/Habilitation': 'Wissenschaftl. Publikation'
  'Personal Interest': 'Persönl. Interesse / Sonstiges'
  'University Teaching/Studies': 'Universitäre Lehre'
  'Genealogical Research': 'Familienforschung'
  'Universitäre Lehre/Studium': 'Universitäre Lehre'
  'Projektmitarbeit': 'Persönl. Interesse / Sonstiges'
  'Publikation': 'Wissenschaftl. Publikation'
  'Pers?ches Interesse': 'Persönl. Interesse / Sonstiges'
  'Universit?re Lehre': 'Universitäre Lehre'
  'Other': 'Persönl. Interesse / Sonstiges'
  'Teaching': 'Universitäre Lehre'
  'Exhibition': 'Ausstellung'
  'Schulunterricht': 'Schulprojekt/Referat'
  'Art Project': 'Kunstprojekt'
  'Publication': 'Wissenschaftl. Publikation'
  'Publication in Press': 'Pressepublikation'
  'Documentary': 'Dokumentarfilm'
  'School Project/Presentation': 'Schulprojekt/Referat'
