job_description:
  'Sch?lerin/Sch?ler': 'University Student'
  'Schülerin/Schüler': 'University Student'
  'student': 'University Student'
  'Student(in)': 'University Student'
  'Studentin/Student': 'University Student'
  'University Student': 'University Student'
  'Студент': 'University Student'

  'k. A. (Beruf)': 'Other (job description)'
  'Other (job description)': 'Other (job description)'
  'other': 'Other (job description)'
  'Other': 'Other (job description)'
  'Sonstiges': 'Other (job description)'
  'Прочее': 'Other (job description)'

  'Lehrer(in)': 'Teacher'
  'Lehrerin/Lehrer': 'Teacher'
  'teacher': 'Teacher'
  'Teacher': 'Teacher'
  'Учитель': 'Teacher'

  'Dozent': 'Lecturer/Researcher'
  'Dozent(in)/Forscher(in)': 'Lecturer/Researcher'
  'Dozentin/Dozent': 'Lecturer/Researcher'
  'Lecturer': 'Lecturer/Researcher'
  'Lecturer/Researcher': 'Lecturer/Researcher'
  'researcher': 'Lecturer/Researcher'
  'Wissenschaftlerin/Wissenschaftler': 'Lecturer/Researcher'
  'Доцент/Научный сотрудник': 'Lecturer/Researcher'

  'journalist': 'Journalist'
  'Journalist': 'Journalist'
  'Journalist(in)': 'Journalist'
  'Journalistin/Journalist': 'Journalist'
  'Журналист': 'Journalist'

  'pupil': 'Pupil'
  'Pupil': 'Pupil'  
  'School Student': 'Pupil'
  'Schüler(in)': 'Pupil'
  'Учащийся': 'Pupil'

  'Filmemacher(in)': 'Filmmaker'
  'Filmemacherin/Filmemacher': 'Filmmaker'
  'filmmaker': 'Filmmaker'
  'Filmmaker': 'Filmmaker'
  'Автор фильмов': 'Filmmaker'

  'memorial_staff': 'Staff Member (Museums/Memorial Sites)'
  'Mitarbeiter(in) (Museen/Gedenkstätten)': 'Staff Member (Museums/Memorial Sites)'
  'Mitarbeiterin /Mitarbeiter (Museen / Gedenkst?tten)': 'Staff Member (Museums/Memorial Sites)'
  'Mitarbeiterin /Mitarbeiter (Museen / Gedenkstätten)': 'Staff Member (Museums/Memorial Sites)'
  'Mitarbeiterin/Mitarbeiter (Museen/Gedenkstätten)': 'Staff Member (Museums/Memorial Sites)'
  'Staff Member (Museums/Memorial Sites)': 'Staff Member (Museums/Memorial Sites)'
  'Сотрудник (Музеи/Мемориалы)': 'Staff Member (Museums/Memorial Sites)'

  'Mitarbeit': 'Project Staff (job description)'
  'Project Staff (job description)': 'Project Staff (job description)'
  'Projektmitarbeiter': 'Project Staff (job description)'
  
research_intentions:
  'Ausstellung': 'Exhibition'
  'exhibition': 'Exhibition'
  'Exhibition': 'Exhibition'
  'Выставка': 'Exhibition'

  'Familienforschung': 'Genealogy'
  'Genealogical Research': 'Genealogy'
  'genealogy': 'Genealogy'
  'Genealogy': 'Genealogy'
  'Семейные исследования': 'Genealogy'

  'Pers?ches Interesse': 'Personal Interest'
  'Pers?nliches Interesse': 'Personal Interest'
  'Personal Interest / Other': 'Personal Interest'
  'Personal Interest': 'Personal Interest'
  'Personal Interest/Other': 'Personal Interest'
  'personal_interest': 'Personal Interest'
  'Persönl. Interesse / Sonstiges': 'Personal Interest'
  'Persönliches Interesse': 'Personal Interest'
  'Private Interest/Other': 'Personal Interest'
  'Личный интерес': 'Personal Interest'

  'Bildungsarbeit': 'Educational Work'
  'education': 'Educational Work'
  'Educational Work': 'Educational Work'
  'Просветительная работа': 'Educational Work'

  'School Project/Presentation': 'School Project/Presentation'
  'school_project': 'School Project/Presentation'
  'Schulprojekt/Referat': 'School Project/Presentation'
  'Школьный проект/реферат': 'School Project/Presentation'

  'Teaching': 'University Course/Lecture'
  'Universit?re Lehre': 'University Course/Lecture'
  'Universitäre Lehre': 'University Course/Lecture'
  'Universitäre Lehre/Studium': 'University Course/Lecture'
  'University Course/Lecture': 'University Course/Lecture'
  'University Teaching/Studies': 'University Course/Lecture'
  'university_teaching': 'University Course/Lecture'
  'Университетское преподавание': 'University Course/Lecture'

  'Dissertation': 'Scholarly Publication'
  'Dissertation/Habilitation': 'Scholarly Publication'
  'Publication': 'Scholarly Publication'
  'Publikation': 'Scholarly Publication'
  'Scholarly Publication': 'Scholarly Publication'
  'scientific_paper': 'Scholarly Publication'
  'Wissenschaftliche Publikation': 'Scholarly Publication'
  'Диссертация': 'Scholarly Publication'
  'Научная публикация': 'Scholarly Publication'

  'Press Publication': 'Publication in Press'
  'press_publishing': 'Publication in Press'
  'Pressepublikation': 'Publication in Press'
  'Publication in Press': 'Publication in Press'
  'Публикация в прессе': 'Publication in Press'

  'School Project/Presentation': 'School Project/Presentation'
  'school_project': 'School Project/Presentation'
  'Schulunterricht': 'School Project/Presentation'

  'Documentary Film': 'Documentary Film'
  'Documentary': 'Documentary Film'
  'Dokumentarfilm': 'Documentary Film'
  'film': 'Documentary Film'
  'Документальный фильм': 'Documentary Film'

  'art': 'Art Project'
  'Art Project': 'Art Project'
  'Kunstprojekt': 'Art Project'
  'Проект в области искусства': 'Art Project'

  'Mitarbeit': 'Project Staff (research intentions)'
  'Project Staff (research intentions)': 'Project Staff (research intentions)'
  'Projektmitarbeit': 'Project Staff (research intentions)'

  'k. A. (Recherche-Anliegen)': 'Other (research intentions)'
  'k.A. (Recherche-Anliegen)': 'Other (research intentions)'
  'Other (research intentions)': 'Other (research intentions)'
  'other': 'Other (research intentions)'
  'Other': 'Other (research intentions)'
  'Sonstiges': 'Other (research intentions)'
  'Прочее': 'Other (research intentions)'