# Sunspot Solr configuration

defaults: &defaults
    hostname: localhost
    port: 8985
    path: /solr/default
    log_level: WARNING

development:
  solr:
    <<: *defaults
    log_level: INFO

test:
  solr:
    <<: *defaults

cucumber:
  solr:
    <<: *defaults
    log_level: INFO

production:
  solr:
    <<: *defaults
    port: 8090
    path: /solr_zwar_demo
    # read_timeout: 2
    # open_timeout: 0.5
