# Sunspot Solr configuration

defaults: &defaults
  solr:
    hostname: localhost
    port: 8985
    path: /solr

development:
  <<: *defaults

test:
  <<: *defaults
  solr:
    port: 8986

production:
  <<: *defaults
  solr:
    port: 8090
    path: /solr_zwar_demo