collection:
  key_attributes: 'project_id'
  project-id: 'project_id'
  title: 'name'
  countries: 'countries'
  institution: 'institution'
  homepage: 'homepage'
  interviewers: 'interviewers'
  responsibles: 'responsibles'
  notes: 'notes'

interview:
  key_attributes: 'archive_id'
  archive-id: 'archive_id'
  duration: 'duration'
  interview-date: 'interview_date'
  still-content-type: 'still_image_content_type'
  still-file-name: 'still_image_file_name'
  still-file-size: 'still_image_file_size'
  translated: 'translated'
  video:  'video'
  original-citation: 'original_citation'
  translated-citation: 'translated_citation'
  citation-timecode: 'citation_timecode'
  citation-media-id: 'citation_media_id'

  language:
    name: 'languages'
    code: 'language_codes'

  person:
    alias-names: 'alias_names'
    gender: 'gender'
    country-of-origin: 'country_of_origin'
    date-of-birth: 'date_of_birth'
    deportation-date: 'deportation_date'
    details-of-origin: 'details_of_origin'
    firstname: 'first_name'
    middle-names: 'other_first_names'
    lastname: 'last_name'
    birth-name: 'birth_name'
    forced-labor-details: 'forced_labor_details'
    punishment: 'punishment'
    liberation-date: 'liberation_date'
    return-date: 'return_date'
    forced-labor-groups: 'forced_labor_groups'
    forced-labor-habitations: 'forced_labor_habitations'
    forced-labor-fields: 'forced_labor_fields'

interview-team-member:
  class_name: 'contribution'
  delete_all: true
  delete_orphans_from: 'contributor'
  skip_invalid: true
  first-name: 'first_name'
  last-name: 'last_name'
  task: 'contribution_type'

photo:
  key_attributes: 'photo_file_name'
  delete_all: true
  skip_invalid: true # I don't like it, but at least they get reported
  image-file-name: 'photo_file_name'
  caption: 'caption'

tape:
  media-id: 'media_id'
  duration: 'duration'
  skip_invalid: true
  delete_all: true

text-material:
  class_name: 'text_material'
  key_attributes: 'document_type|locale'
  delete_all: true
  document-type: 'document_type'
  document-file-name: 'document_file_name'
  locale: 'locale'
  skip_invalid: true

caption:
  class_name: 'segment'
  key_attributes: 'none'
  delete_all: true
  media-id: 'media_id'
  timecode: 'timecode'
  duration: 'duration'
  transcript: 'transcript'
  translation: 'translation'
  mainheading: 'mainheading'
  subheading: 'subheading'
  section-code: 'section'
  speaker-change: 'speaker_change'
  chapter-change: 'chapter_change'
  speaker: 'speaker'

location:
  class_name: 'location_reference'
  key_attributes: 'none'
  delete_all: true
  skip_invalid: true
  place-type: 'location_type'
  descriptor: 'name'
  related-to: 'reference_type'
  camp-category: 'camp_type'
  workflow-state: 'workflow_state'
  physical-location:
    name: 'location_name'
    longitude: 'longitude'
    latitude: 'latitude'
    city:
      name: 'city_name'
      alias-names: 'city_alias_names'
    region:
      name: 'region_name'
      latitude: 'region_latitude'
      longitude: 'region_longitude'
      alias-names: 'region_alias_names'
    country:
      name: 'country_name'
      latitude: 'country_latitude'
      longitude: 'country_longitude'
      alias-names: 'country_alias_names'
  camp:
    name: 'camp_name'
    alias-names: 'camp_alias_names'
    classification: 'camp_classification'
    description: 'description'
    latitude: 'exact_latitude'
    longitude: 'exact_longitude'
  company:
    name: 'company_name'
    alias-names: 'company_alias_names'
    description: 'description'
    latitude: 'exact_latitude'
    longitude: 'exact_longitude'

locations-segment:
  class_name: 'location_segment'
  key_attributes: 'none'
  skip_invalid: true
  media-id: 'media_id'
  descriptor: 'descriptor'

annotation:
  key_attributes: 'none'
  delete_all: true
  skip_invalid: true
  author: 'author'
  media-id: 'media_id'
  timecode: 'timecode'
  text: 'text'
